version: '3.9'
services:
  app:
    environment:
      - TZ=Asia/Bangkok
    build: .
    container_name: occurrence-report-app
    volumes:
      - ./project/backend:/app
      - ./project/backend/node_modules:/app/node_modules
      - ./project/frontend:/app/frontend
      - ./project/frontend/node_modules:/app/frontend/node_modules
      - ./nginx/http.d/:/etc/nginx/http.d/
      #- /mnt/tnh-fileserver:/app/tnh-fileserver
    ports:
      - '8137:80'
    restart: always